repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        exclude: ^apps/.*/migrations/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        exclude: ^docs/
        additional_dependencies:
          - django-stubs==5.1.1
          - djangorestframework-stubs==3.15.1
          - types-requests==2.32.0.20241016
