# Generated by Django 5.2.5 on 2025-09-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importa_arquivos", "0003_importacaoarquivohabilitado_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importacaoarquivovagas",
            name="concurso_nome",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nome do concurso"
            ),
        ),
        migrations.AddField(
            model_name="importacaoarquivovagas",
            name="concurso_uuid",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="UUID do concurso"
            ),
        ),
    ]
