# Generated by Django 5.2.5 on 2025-10-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importa_arquivos", "0004_importacaoarquivovagas_concurso_nome_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importacaoarquivovagas",
            name="concurso_nome",
        ),
        migrations.RemoveField(
            model_name="importacaoarquivovagas",
            name="concurso_uuid",
        ),
        migrations.AddField(
            model_name="importacaoarquivovagas",
            name="processo_nome",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nome do processo de convocação",
            ),
        ),
        migrations.AddField(
            model_name="importacaoarquivovagas",
            name="processo_uuid",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="UUID do processo de convocação"
            ),
        ),
    ]
