# Generated by Django 5.2.5 on 2026-03-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importa_arquivos", "0008_add_importacao_lotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="importacaolotes",
            name="detalhes",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Detalhes da Atualização"
            ),
        ),
    ]
