# Generated by Django 5.2.5 on 2026-06-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "importa_arquivos",
            "0010_remove_importacaolotes_erros_importacaolotes_tipo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="importacaoarquivovagas",
            name="concurso_uuid",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="UUID do concurso"
            ),
        ),
    ]
