# Generated by Django 5.2.5 on 2026-07-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importa_arquivos", "0011_importacaoarquivovagas_concurso_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="importacaoarquivohabilitado",
            name="observacao",
            field=models.TextField(blank=True, null=True, verbose_name="Observação"),
        ),
        migrations.AddField(
            model_name="importacaoarquivohabilitado",
            name="quantidade",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Quantidade de registros"
            ),
        ),
    ]
