# Generated by Django 5.2.5 on 2026-08-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importa_arquivos', '0012_importacaoarquivohabilitado_observacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaoescolhas',
            name='modo',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICA', 'Automática')], default='MANUAL', max_length=20, verbose_name='Modo'),
        ),
    ]
