# Generated by Django 5.2.5 on 2025-09-11 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportacaoArquivoHabilitado",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "nome_arquivo",
                    models.CharField(max_length=200, verbose_name="Nome do Arquivo"),
                ),
                (
                    "arquivo",
                    models.FileField(upload_to="importacoes/", verbose_name="Arquivo"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("HABILITADOS", "Habilitados"), ("VAGAS", "Vagas")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PROCESSANDO", "Processando"),
                            ("CONCLUIDO", "Concluído"),
                            ("ERRO", "Erro"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("concurso_uuid", models.UUIDField(verbose_name="UUID do concurso")),
                (
                    "concurso_nome",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome do concurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Importação de arquivo habilitado",
                "verbose_name_plural": "Importações de arquivos habilitados",
                "db_table": "importacao_arquivo_habilitado",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ImportacaoArquivoVagas",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "nome_arquivo",
                    models.CharField(max_length=200, verbose_name="Nome do Arquivo"),
                ),
                (
                    "arquivo",
                    models.FileField(upload_to="importacoes/", verbose_name="Arquivo"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("HABILITADOS", "Habilitados"), ("VAGAS", "Vagas")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PROCESSANDO", "Processando"),
                            ("CONCLUIDO", "Concluído"),
                            ("ERRO", "Erro"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Importação de arquivo de vagas",
                "verbose_name_plural": "Importações de arquivos de vagas",
                "db_table": "importacao_arquivo_vagas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="LayoutArquivoImportacao",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("HABILITADOS", "Habilitados"), ("VAGAS", "Vagas")],
                        default="HABILITADOS",
                        max_length=20,
                        verbose_name="Tipo de arquivo",
                    ),
                ),
                ("estrutura", models.JSONField(verbose_name="Estrutura do arquivo")),
            ],
            options={
                "verbose_name": "Layout de importação de arquivo",
                "verbose_name_plural": "Layouts de importação de arquivos",
                "db_table": "layout_arquivo_importacao",
                "ordering": ["-criado_em"],
            },
        ),
    ]
