# Generated by Django 5.2.5 on 2025-09-03 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importa_arquivos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Layout",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "tipo_de_layout",
                    models.CharField(
                        choices=[
                            ("VAGAS", "Vagas"),
                            ("CANDIDATOS_CLASSIFICADOS", "Candidatos Classificados"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Layout",
                    ),
                ),
                (
                    "dados",
                    models.JSONField(
                        help_text="Lista de campos com estrutura: ordem, campo, tipo, tamanho, regras_de_validacao",
                        verbose_name="Dados do Layout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Layout",
                "verbose_name_plural": "Layouts",
                "db_table": "layout",
                "ordering": ["-criado_em"],
            },
        ),
    ]
