# Generated by Django 5.2.5 on 2025-09-25 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("importa_arquivos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportacaoErro",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "mensagem",
                    models.CharField(
                        max_length=255, verbose_name="Mensagem curta do erro"
                    ),
                ),
                ("erros", models.TextField(verbose_name="Erros da importação")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Erro de Importação",
                "verbose_name_plural": "Erros de Importação",
                "db_table": "importacao_erros",
                "ordering": ["-criado_em"],
            },
        ),
    ]
