# Generated by Django 5.2.5 on 2025-09-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importa_arquivos", "0002_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="importacaoarquivos",
            name="tipo_de_layout",
            field=models.CharField(
                choices=[
                    ("VAGAS", "Vagas"),
                    ("CANDIDATOS_CLASSIFICADOS", "Candidatos Classificados"),
                ],
                default="VAGAS",
                help_text="Tipo de layout que define a estrutura dos dados do arquivo",
                max_length=30,
                verbose_name="Tipo de Layout",
            ),
        ),
    ]
