# Generated by Django 5.2.5 on 2025-09-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importa_arquivos", "0003_importacaoarquivos_tipo_de_layout"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importacaoarquivos",
            name="arquivo",
        ),
        migrations.AddField(
            model_name="importacaoarquivos",
            name="arquivo_content_type",
            field=models.CharField(
                default="text/csv", max_length=100, verbose_name="Tipo do Arquivo"
            ),
        ),
        migrations.AddField(
            model_name="importacaoarquivos",
            name="arquivo_nome_original",
            field=models.CharField(
                default="arquivo.csv",
                max_length=255,
                verbose_name="Nome do Arquivo Original",
            ),
        ),
        migrations.AddField(
            model_name="importacaoarquivos",
            name="arquivo_tamanho",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tamanho do Arquivo (bytes)"
            ),
        ),
    ]
