# Generated by Django 5.2.5 on 2025-09-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importa_arquivos", "0004_remove_arquivo_field_add_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importacaoarquivos",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="importacaoarquivos",
            name="nome",
        ),
        migrations.AddField(
            model_name="importacaoarquivos",
            name="cargo",
            field=models.CharField(default="", max_length=255, verbose_name="Cargo"),
        ),
        migrations.AddField(
            model_name="importacaoarquivos",
            name="concurso",
            field=models.CharField(default="", max_length=255, verbose_name="Concurso"),
        ),
        migrations.AlterField(
            model_name="importacaoarquivos",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("processando", "Processando"),
                    ("concluido", "Concluido"),
                    ("erro", "Erro"),
                ],
                default="pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
