# Generated by Django 5.2.5 on 2025-09-08 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("importa_arquivos", "0005_remove_fields_add_concurso_cargo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Layout",
        ),
    ]
