# Generated by Django 5.2.5 on 2026-02-06 13:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importa_arquivos", "0006_insert_layouts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportacaoEscolhas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "processo_uuid",
                    models.UUIDField(
                        blank=True,
                        null=True,
                        verbose_name="UUID do processo de convocação",
                    ),
                ),
                (
                    "processo_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID do processo"
                    ),
                ),
                (
                    "concurso_uuid",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="UUID do concurso"
                    ),
                ),
                (
                    "dados_prodam",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Dados da importação da API PRODAM",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PROCESSANDO", "Processando"),
                            ("CONCLUIDO", "Concluído"),
                            ("ERRO", "Erro"),
                        ],
                        default="CONCLUIDO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Importação de escolhas",
                "verbose_name_plural": "Importações de escolhas",
                "db_table": "importacao_escolhas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="LogRequestHttp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="URL chamada")),
                (
                    "metodo_http",
                    models.CharField(max_length=10, verbose_name="Método HTTP"),
                ),
                (
                    "processo_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID do processo"
                    ),
                ),
                (
                    "resposta_raw",
                    models.TextField(verbose_name="Resposta raw (sem formatação)"),
                ),
            ],
            options={
                "verbose_name": "Log de requisição HTTP",
                "verbose_name_plural": "Log de requisição HTTP",
                "db_table": "log_request_http",
                "ordering": ["-criado_em"],
            },
        ),
    ]
