# Generated by Django 5.2.5 on 2025-09-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importa_arquivos", "0006_remove_layout_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importacaoarquivos",
            name="tipo_de_layout",
            field=models.CharField(
                choices=[("VAGAS", "Vagas"), ("HABILITADOS", "Habilitados")],
                default="VAGAS",
                help_text="Tipo de layout que define a estrutura dos dados do arquivo",
                max_length=30,
                verbose_name="Tipo de Layout",
            ),
        ),
    ]
