# Generated by Django 5.2.5 on 2026-03-23 03:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importa_arquivos", "0007_importacaoescolhas_logrequesthttp"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportacaoLotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "nome_arquivo",
                    models.CharField(max_length=200, verbose_name="Nome do Arquivo"),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="importacoes_lotes/", verbose_name="Arquivo"
                    ),
                ),
                ("concurso_uuid", models.UUIDField(verbose_name="UUID do Concurso")),
                (
                    "concurso_nome",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome do Concurso",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CONCLUIDO", "Concluído"),
                            ("ERRO", "Erro"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_atualizados",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total de Candidatos Atualizados",
                    ),
                ),
                (
                    "erros",
                    models.TextField(blank=True, null=True, verbose_name="Erros"),
                ),
            ],
            options={
                "verbose_name": "Importação de Lotes",
                "verbose_name_plural": "Importações de Lotes",
                "db_table": "importacao_lotes",
                "ordering": ["-criado_em"],
            },
        ),
    ]
