# Generated by Django 5.2.5 on 2026-03-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importa_arquivos", "0009_add_detalhes_importacao_lotes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importacaolotes",
            name="erros",
        ),
        migrations.AddField(
            model_name="importacaolotes",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("HABILITADOS", "Habilitados"),
                    ("VAGAS", "Vagas"),
                    ("LOTES", "Lotes"),
                ],
                default="LOTES",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="importacaoarquivohabilitado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("HABILITADOS", "Habilitados"),
                    ("VAGAS", "Vagas"),
                    ("LOTES", "Lotes"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="importacaoarquivovagas",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("HABILITADOS", "Habilitados"),
                    ("VAGAS", "Vagas"),
                    ("LOTES", "Lotes"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="importacaolotes",
            name="arquivo",
            field=models.FileField(upload_to="importacoes/", verbose_name="Arquivo"),
        ),
        migrations.AlterField(
            model_name="importacaolotes",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("PROCESSANDO", "Processando"),
                    ("CONCLUIDO", "Concluído"),
                    ("ERRO", "Erro"),
                ],
                default="PENDENTE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="layoutarquivoimportacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("HABILITADOS", "Habilitados"),
                    ("VAGAS", "Vagas"),
                    ("LOTES", "Lotes"),
                ],
                default="HABILITADOS",
                max_length=20,
                verbose_name="Tipo de arquivo",
            ),
        ),
    ]
