# Generated by Django 5.2.5 on 2026-03-13 18:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exporta_arquivo", "0002_add_exportacao_vagas_processo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportacaoCandidatosProcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "processo_uuid",
                    models.UUIDField(verbose_name="UUID do processo de convocação"),
                ),
                ("cargo_uuid", models.UUIDField(verbose_name="UUID do cargo")),
                (
                    "concurso_uuid",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="UUID do concurso"
                    ),
                ),
                (
                    "concurso_nome",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome do concurso",
                    ),
                ),
                (
                    "concurso_codigo",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Código do concurso"
                    ),
                ),
                (
                    "concurso_data_criacao",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Data de criação do concurso",
                    ),
                ),
                (
                    "processo_nome",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Nome do processo",
                    ),
                ),
                (
                    "cargo_nome",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome do cargo",
                    ),
                ),
                (
                    "cargo_codigo",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Código do cargo (integração)",
                    ),
                ),
                (
                    "conteudo_arquivo",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Conteúdo do arquivo exportado",
                    ),
                ),
                (
                    "nome_arquivo",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome do arquivo na exportação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exportação de candidatos processo",
                "verbose_name_plural": "Exportações de candidatos processo",
                "db_table": "exportacao_candidatos_processo",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="exportacaovagasprocesso",
            name="cargo_codigo",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Código do cargo (integração)"
            ),
        ),
        migrations.AddField(
            model_name="exportacaovagasprocesso",
            name="cargo_nome",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nome do cargo"
            ),
        ),
        migrations.AddField(
            model_name="exportacaovagasprocesso",
            name="conteudo_arquivo",
            field=models.TextField(
                blank=True, null=True, verbose_name="Conteúdo do arquivo exportado"
            ),
        ),
        migrations.AddField(
            model_name="exportacaovagasprocesso",
            name="nome_arquivo",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nome do arquivo na exportação",
            ),
        ),
        migrations.AddField(
            model_name="exportacaovagasprocesso",
            name="processo_nome",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Nome do processo"
            ),
        ),
        migrations.AddField(
            model_name="exportacaovagassigpec",
            name="cargo_codigo",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Código do cargo (integração)"
            ),
        ),
        migrations.AddField(
            model_name="exportacaovagassigpec",
            name="cargo_nome",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nome do cargo"
            ),
        ),
        migrations.AddField(
            model_name="exportacaovagassigpec",
            name="conteudo_arquivo",
            field=models.TextField(
                blank=True, null=True, verbose_name="Conteúdo do arquivo exportado"
            ),
        ),
        migrations.AddField(
            model_name="exportacaovagassigpec",
            name="nome_arquivo",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nome do arquivo na exportação",
            ),
        ),
        migrations.AddField(
            model_name="exportacaovagassigpec",
            name="processo_nome",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Nome do processo"
            ),
        ),
    ]
