# Generated by Django 5.2.5 on 2026-03-27 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "exporta_arquivo",
            "0004_alter_exportacaocandidatosprocesso_concurso_data_criacao",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CabecalhoExportacaoLote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "tabela",
                    models.CharField(
                        default="[c_ERGON][PMSP_ESCOLHA_VAGA_SME][1.0]",
                        max_length=500,
                        verbose_name="@TABELA",
                    ),
                ),
                (
                    "chave",
                    models.CharField(
                        default="[ID_LOTE][NUMBER][EMP_CODIGO][NUMBER][CHAVE_INSCRITO][NUMBER]",
                        max_length=500,
                        verbose_name="@CHAVE",
                    ),
                ),
                (
                    "tag_inicio",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="@TAG INICIO",
                    ),
                ),
                (
                    "tag_fim",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="@TAG FIM"
                    ),
                ),
                (
                    "separador",
                    models.CharField(
                        default=";", max_length=10, verbose_name="@SEPARADOR"
                    ),
                ),
                (
                    "formato_data",
                    models.CharField(
                        default="DD/MM/YYYY",
                        max_length=50,
                        verbose_name="@FORMATO DATA",
                    ),
                ),
                (
                    "colunas",
                    models.CharField(
                        default="[ID_LOTE][NUMBER][EMP_CODIGO][NUMBER][CHAVE_INSCRITO][NUMBER][DATA_ESCOLHA][DATE][ESCOLHEU_VAGA][VARCHAR2][SETOR][VARCHAR2]",
                        max_length=1000,
                        verbose_name="@COLUNAS",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Cabeçalho de Exportação de Lote",
                "verbose_name_plural": "Cabeçalhos de Exportação de Lote",
                "db_table": "cabecalho_exportacao_lote",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ExportacaoLote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PROCESSANDO", "Processando"),
                            ("SUCESSO", "Sucesso"),
                            ("ERRO", "Erro"),
                        ],
                        default="SUCESSO",
                        max_length=20,
                        verbose_name="Status da Exportação",
                    ),
                ),
                ("concurso_uuid", models.UUIDField(verbose_name="UUID do Concurso")),
                (
                    "concurso_nome",
                    models.CharField(max_length=255, verbose_name="Nome do Concurso"),
                ),
                ("lote_uuid", models.UUIDField(verbose_name="UUID do Lote")),
                ("numero_lote", models.IntegerField(verbose_name="Número do Lote")),
                (
                    "codigo_cargo",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Código do Cargo",
                    ),
                ),
                (
                    "conteudo_arquivo",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Conteúdo do arquivo exportado",
                    ),
                ),
                (
                    "nome_arquivo",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome do arquivo exportado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exportação de Lote",
                "verbose_name_plural": "Exportações de Lote",
                "db_table": "exportacao_lote",
                "ordering": ["-criado_em"],
            },
        ),
    ]
