# Generated by Django 5.2.5 on 2026-03-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exporta_arquivo", "0003_exportacaocandidatosprocesso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportacaocandidatosprocesso",
            name="concurso_data_criacao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de criação do concurso"
            ),
        ),
    ]
